# Generated by Django 4.1.1 on 2022-10-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_cpf_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='complemtento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
